#!/usr/bin/env ruby
# https://raw.github.com/tsaleh/dotfiles/master/vim/update_bundles
# Ideally, there would be a way to "include" just this file as a submodule or 
# similar or similar thing.

# TODO:
# Look through the rest of tpope's and tsaleh's Vim scripts
# Search for more "python vim" goodies
# Try: git://github.com/hynek/vim-python-pep8-indent.git
# Try: https://github.com/klen/python-mode

git_bundles = %w{
  git://github.com/tpope/vim-pathogen.git
  git://github.com/msanders/snipmate.vim.git
  git://github.com/wincent/Command-T.git
  git://github.com/tomtom/tcomment_vim.git
  git://github.com/tpope/vim-repeat.git
  git://github.com/tpope/vim-surround.git
  git://github.com/nathanaelkane/vim-indent-guides.git
  git://github.com/tsaleh/vim-matchit.git
  git://github.com/godlygeek/tabular.git
  git://github.com/pangloss/vim-javascript.git
}

vim_org_scripts = [
  ["python", "17429", "syntax"],
  ["html",   "16508", "indent"],
]

require 'fileutils'
require 'open-uri'

bundles_dir = File.join(File.dirname(__FILE__), "bundle")

FileUtils.rm_rf(bundles_dir)
FileUtils.mkdir(bundles_dir)
FileUtils.cd(bundles_dir)

git_bundles.each do |url|
  puts url
  `git clone -q #{url}`
end

Dir["*/.git"].each {|f| FileUtils.rm_rf(f) }

vim_org_scripts.each do |name, script_id, script_type|
  puts "vim.org script: #{name}"
  local_file = File.join("vim.org", script_type, "#{name}.vim")
  FileUtils.mkdir_p(File.dirname(local_file))
  File.open(local_file, "w") do |file|
    file << open("http://www.vim.org/scripts/download_script.php?src_id=#{script_id}").read
  end
end

# Build the Command-T Ruby C extension
puts "Building Command-T's C extension..."
cmdt_ext_dir = File.join("Command-T", "ruby", "command-t")
FileUtils.cd(cmdt_ext_dir)
`ruby extconf.rb`
`ARCHFLAGS="-arch i386" make`

