#!/usr/bin/env ruby
# https://raw.github.com/tsaleh/dotfiles/master/vim/update_bundles
# Ideally, there would be a way to "include" just this file as a submodule or 
# similar or similar thing.

git_bundles = %w{
  git://github.com/tpope/vim-pathogen.git
  git://github.com/msanders/snipmate.vim.git
  git://github.com/wincent/Command-T.git
}

require 'fileutils'
require 'open-uri'

bundles_dir = File.join(File.dirname(__FILE__), "bundle")

FileUtils.rm_rf(bundles_dir)
FileUtils.mkdir(bundles_dir)
FileUtils.cd(bundles_dir)

git_bundles.each do |url|
  puts url
  `git clone -q #{url}`
end

Dir["*/.git"].each {|f| FileUtils.rm_rf(f) }

